# rathole configuration for proxy protocol enabled client
# 
# The client configuration is essentially unaffected, since the proxy
# protocol header would be transarently passed to the downstream server.

[client]
remote_addr = "localhost:2333"
default_token = "123"

[client.services.foo1]
local_addr = "127.0.0.1:80"
